// Generated by delombok at Sat Jun 13 00:47:29 UTC 2026
package gov.cms.fiss.pricers.ltch.api.v2;

import gov.cms.fiss.pricers.common.api.ClaimPricingRequest;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "The LTCH claim input for processing.")
public class LtchClaimPricingRequest extends ClaimPricingRequest<LtchClaimData, LtchInpatientProviderData> {
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LtchClaimPricingRequest)) return false;
        final LtchClaimPricingRequest other = (LtchClaimPricingRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof LtchClaimPricingRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int result = super.hashCode();
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "LtchClaimPricingRequest()";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LtchClaimPricingRequest() {
    }
}
