// Generated by delombok at Sat Jun 13 00:47:29 UTC 2026
package gov.cms.fiss.pricers.ltch.api.v1;

import gov.cms.fiss.pricers.common.api.TableEntryRetrievalResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import java.util.ArrayList;
import java.util.List;

@Schema(description = "Response containing aggregate long-term care hospital DRG data.")
public class LtchDrgRetrievalResponse implements TableEntryRetrievalResponse<LtchDrgsTableEntry> {
  @Valid
  private List<LtchDrgsTableEntry> tableEntries = new ArrayList<>();

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public LtchDrgRetrievalResponse(final List<LtchDrgsTableEntry> tableEntries) {
    this.tableEntries = tableEntries;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public List<LtchDrgsTableEntry> getTableEntries() {
    return this.tableEntries;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setTableEntries(final List<LtchDrgsTableEntry> tableEntries) {
    this.tableEntries = tableEntries;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof LtchDrgRetrievalResponse)) return false;
    final LtchDrgRetrievalResponse other = (LtchDrgRetrievalResponse) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$tableEntries = this.getTableEntries();
    final java.lang.Object other$tableEntries = other.getTableEntries();
    if (this$tableEntries == null ? other$tableEntries != null : !this$tableEntries.equals(other$tableEntries)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof LtchDrgRetrievalResponse;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $tableEntries = this.getTableEntries();
    result = result * PRIME + ($tableEntries == null ? 43 : $tableEntries.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public java.lang.String toString() {
    return "LtchDrgRetrievalResponse(tableEntries=" + this.getTableEntries() + ")";
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public LtchDrgRetrievalResponse() {
  }
}
