// Generated by delombok at Wed Jul 01 19:51:07 UTC 2026
package gov.cms.fiss.pricers.ipps.api.v1;

import gov.cms.fiss.pricers.common.api.TableEntryRetrievalResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import java.util.ArrayList;
import java.util.List;

@Schema(description = "Response containing aggregate DRG data.")
public class DrgRetrievalResponse implements TableEntryRetrievalResponse<DrgsTableEntry> {
  @Valid
  private List<DrgsTableEntry> tableEntries = new ArrayList<>();

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public DrgRetrievalResponse(final List<DrgsTableEntry> tableEntries) {
    this.tableEntries = tableEntries;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public List<DrgsTableEntry> getTableEntries() {
    return this.tableEntries;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setTableEntries(final List<DrgsTableEntry> tableEntries) {
    this.tableEntries = tableEntries;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof DrgRetrievalResponse)) return false;
    final DrgRetrievalResponse other = (DrgRetrievalResponse) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    final java.lang.Object this$tableEntries = this.getTableEntries();
    final java.lang.Object other$tableEntries = other.getTableEntries();
    if (this$tableEntries == null ? other$tableEntries != null : !this$tableEntries.equals(other$tableEntries)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof DrgRetrievalResponse;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final java.lang.Object $tableEntries = this.getTableEntries();
    result = result * PRIME + ($tableEntries == null ? 43 : $tableEntries.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public java.lang.String toString() {
    return "DrgRetrievalResponse(tableEntries=" + this.getTableEntries() + ")";
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public DrgRetrievalResponse() {
  }
}
