// Generated by delombok at Fri Jun 05 14:59:17 UTC 2026
package gov.cms.fiss.pricers.esrd.api.v2;

import gov.cms.fiss.pricers.common.api.ClaimPricingResponse;
import io.swagger.v3.oas.annotations.extensions.Extension;
import io.swagger.v3.oas.annotations.extensions.ExtensionProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;

@Schema(description = "The ESRD claim output from processing.", extensions = @Extension(name = "cobol-declaration", properties = @ExtensionProperty(name = "PPS-DATA-ALL", value = "<structure>")))
public class EsrdClaimPricingResponse extends ClaimPricingResponse<EsrdPaymentData> {
  @Valid
  private AdditionalPricingData additionalPricingInformation = new AdditionalPricingData();
  @Valid
  private BundledBillingData bundledBillingInformation = new BundledBillingData();
  @Valid
  private OutlierBillingData outlierBillingInformation = new OutlierBillingData();
  @Valid
  private PaymentBillingData paymentBillingInformation = new PaymentBillingData();

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public AdditionalPricingData getAdditionalPricingInformation() {
    return this.additionalPricingInformation;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public BundledBillingData getBundledBillingInformation() {
    return this.bundledBillingInformation;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public OutlierBillingData getOutlierBillingInformation() {
    return this.outlierBillingInformation;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public PaymentBillingData getPaymentBillingInformation() {
    return this.paymentBillingInformation;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setAdditionalPricingInformation(final AdditionalPricingData additionalPricingInformation) {
    this.additionalPricingInformation = additionalPricingInformation;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setBundledBillingInformation(final BundledBillingData bundledBillingInformation) {
    this.bundledBillingInformation = bundledBillingInformation;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setOutlierBillingInformation(final OutlierBillingData outlierBillingInformation) {
    this.outlierBillingInformation = outlierBillingInformation;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public void setPaymentBillingInformation(final PaymentBillingData paymentBillingInformation) {
    this.paymentBillingInformation = paymentBillingInformation;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public boolean equals(final java.lang.Object o) {
    if (o == this) return true;
    if (!(o instanceof EsrdClaimPricingResponse)) return false;
    final EsrdClaimPricingResponse other = (EsrdClaimPricingResponse) o;
    if (!other.canEqual((java.lang.Object) this)) return false;
    if (!super.equals(o)) return false;
    final java.lang.Object this$additionalPricingInformation = this.getAdditionalPricingInformation();
    final java.lang.Object other$additionalPricingInformation = other.getAdditionalPricingInformation();
    if (this$additionalPricingInformation == null ? other$additionalPricingInformation != null : !this$additionalPricingInformation.equals(other$additionalPricingInformation)) return false;
    final java.lang.Object this$bundledBillingInformation = this.getBundledBillingInformation();
    final java.lang.Object other$bundledBillingInformation = other.getBundledBillingInformation();
    if (this$bundledBillingInformation == null ? other$bundledBillingInformation != null : !this$bundledBillingInformation.equals(other$bundledBillingInformation)) return false;
    final java.lang.Object this$outlierBillingInformation = this.getOutlierBillingInformation();
    final java.lang.Object other$outlierBillingInformation = other.getOutlierBillingInformation();
    if (this$outlierBillingInformation == null ? other$outlierBillingInformation != null : !this$outlierBillingInformation.equals(other$outlierBillingInformation)) return false;
    final java.lang.Object this$paymentBillingInformation = this.getPaymentBillingInformation();
    final java.lang.Object other$paymentBillingInformation = other.getPaymentBillingInformation();
    if (this$paymentBillingInformation == null ? other$paymentBillingInformation != null : !this$paymentBillingInformation.equals(other$paymentBillingInformation)) return false;
    return true;
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  protected boolean canEqual(final java.lang.Object other) {
    return other instanceof EsrdClaimPricingResponse;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public int hashCode() {
    final int PRIME = 59;
    int result = super.hashCode();
    final java.lang.Object $additionalPricingInformation = this.getAdditionalPricingInformation();
    result = result * PRIME + ($additionalPricingInformation == null ? 43 : $additionalPricingInformation.hashCode());
    final java.lang.Object $bundledBillingInformation = this.getBundledBillingInformation();
    result = result * PRIME + ($bundledBillingInformation == null ? 43 : $bundledBillingInformation.hashCode());
    final java.lang.Object $outlierBillingInformation = this.getOutlierBillingInformation();
    result = result * PRIME + ($outlierBillingInformation == null ? 43 : $outlierBillingInformation.hashCode());
    final java.lang.Object $paymentBillingInformation = this.getPaymentBillingInformation();
    result = result * PRIME + ($paymentBillingInformation == null ? 43 : $paymentBillingInformation.hashCode());
    return result;
  }

  @java.lang.Override
  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public java.lang.String toString() {
    return "EsrdClaimPricingResponse(additionalPricingInformation=" + this.getAdditionalPricingInformation() + ", bundledBillingInformation=" + this.getBundledBillingInformation() + ", outlierBillingInformation=" + this.getOutlierBillingInformation() + ", paymentBillingInformation=" + this.getPaymentBillingInformation() + ")";
  }

  @java.lang.SuppressWarnings("all")
  @lombok.Generated
  public EsrdClaimPricingResponse() {
  }
}
