// Generated by delombok at Fri Jun 05 14:59:17 UTC 2026
package gov.cms.fiss.pricers.esrd.api.v2;

import gov.cms.fiss.pricers.common.api.ClaimPricingRequest;
import io.swagger.v3.oas.annotations.extensions.Extension;
import io.swagger.v3.oas.annotations.extensions.ExtensionProperty;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "The ESRD claim input for processing.", extensions = @Extension(name = "cobol-declaration", properties = @ExtensionProperty(name = "BILL-PORTION", value = "<structure>")))
public class EsrdClaimPricingRequest extends ClaimPricingRequest<EsrdClaimData, EsrdOutpatientProviderData> {
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof EsrdClaimPricingRequest)) return false;
        final EsrdClaimPricingRequest other = (EsrdClaimPricingRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof EsrdClaimPricingRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int result = super.hashCode();
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "EsrdClaimPricingRequest()";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public EsrdClaimPricingRequest() {
    }
}
