// Generated by delombok at Wed Jun 10 21:58:38 UTC 2026
package gov.cms.fiss.pricers.irf.api.v2;

import gov.cms.fiss.pricers.common.api.ClaimPricingRequest;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "The IRF claim input for processing.")
public class IrfClaimPricingRequest extends ClaimPricingRequest<IrfClaimData, IrfInpatientProviderData> {
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof IrfClaimPricingRequest)) return false;
        final IrfClaimPricingRequest other = (IrfClaimPricingRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof IrfClaimPricingRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int result = super.hashCode();
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "IrfClaimPricingRequest()";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public IrfClaimPricingRequest() {
    }
}
