// Generated by delombok at Wed Jun 10 21:49:43 UTC 2026
package gov.cms.fiss.pricers.snf.api.v2;

import gov.cms.fiss.pricers.common.api.ClaimPricingRequest;
import io.swagger.v3.oas.annotations.extensions.Extension;
import io.swagger.v3.oas.annotations.extensions.ExtensionProperty;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "The SNF claim input for processing.", extensions = @Extension(name = "cobol-declaration", properties = @ExtensionProperty(name = "SNF-DATA", value = "<structure>")))
public class SnfClaimPricingRequest extends ClaimPricingRequest<SnfClaimData, SnfInpatientProviderData> {
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SnfClaimPricingRequest)) return false;
        final SnfClaimPricingRequest other = (SnfClaimPricingRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SnfClaimPricingRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int result = super.hashCode();
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "SnfClaimPricingRequest()";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public SnfClaimPricingRequest() {
    }
}
