// Generated by delombok at Sat Jun 13 00:43:00 UTC 2026
package gov.cms.fiss.pricers.hospice.api.v2;

import gov.cms.fiss.pricers.common.api.ClaimPricingResponse;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "The Hospice claim output from processing.")
public class HospiceClaimPricingResponse extends ClaimPricingResponse<HospicePaymentData> {
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof HospiceClaimPricingResponse)) return false;
		final HospiceClaimPricingResponse other = (HospiceClaimPricingResponse) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof HospiceClaimPricingResponse;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int result = super.hashCode();
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "HospiceClaimPricingResponse()";
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public HospiceClaimPricingResponse() {
	}
}
