// Generated by delombok at Wed Jun 10 21:57:26 UTC 2026
package gov.cms.fiss.pricers.hha.api.v2;

import gov.cms.fiss.pricers.common.api.ClaimPricingResponse;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "The HHA claim output from processing.")
public class HhaClaimPricingResponse extends ClaimPricingResponse<HhaPaymentData> {
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof HhaClaimPricingResponse)) return false;
		final HhaClaimPricingResponse other = (HhaClaimPricingResponse) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof HhaClaimPricingResponse;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public int hashCode() {
		final int result = super.hashCode();
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public java.lang.String toString() {
		return "HhaClaimPricingResponse()";
	}

	@java.lang.SuppressWarnings("all")
	@lombok.Generated
	public HhaClaimPricingResponse() {
	}
}
