// Generated by delombok at Wed Jul 01 19:51:07 UTC 2026
package gov.cms.fiss.pricers.ipps.api.v2;

import gov.cms.fiss.pricers.common.api.InpatientProviderData;
import gov.cms.fiss.pricers.ipps.api.validation.ValidIppsInpatientProviderData;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Inpatient provider-specific data used in claim price calculations. " + "Entries become valid on the date indicated in the `effectiveDate` field and remain " + "in effect until superseded by an entry with a later effective date.", requiredProperties = {"bedSize", "bundleModel1Discount", "capitalCostToChargeRatio", "capitalExceptionPaymentRate", "capitalIndirectMedicalEducationRatio", "costOfLivingAdjustment", "countyCode", "effectiveDate", "fiscalYearBeginDate", "hrrAdjustment", "internsToBedsRatio", "lowVolumeAdjustmentFactor", "medicaidRatio", "oldCapitalHoldHarmlessRate", "operatingCostToChargeRatio", "passThroughAmountForDirectMedicalEducation", "passThroughAmountForOrganAcquisition", "passThroughTotalAmount", "ppsFacilitySpecificRate", "supplementalSecurityIncomeRatio", "uncompensatedCareAmount", "vbpAdjustment"})
@ValidIppsInpatientProviderData
public class IppsInpatientProviderData extends InpatientProviderData {
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public IppsInpatientProviderData() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof IppsInpatientProviderData)) return false;
        final IppsInpatientProviderData other = (IppsInpatientProviderData) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof IppsInpatientProviderData;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int result = super.hashCode();
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "IppsInpatientProviderData()";
    }
}
