// Generated by delombok at Tue Jun 16 19:11:18 UTC 2026
package gov.cms.fiss.pricers.opps.api.v2;

import gov.cms.fiss.pricers.common.api.ClaimPricingRequest;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "The OPPS claim input for processing.")
public class OppsClaimPricingRequest extends ClaimPricingRequest<OppsClaimData, OppsOutpatientProviderData> {
    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof OppsClaimPricingRequest)) return false;
        final OppsClaimPricingRequest other = (OppsClaimPricingRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof OppsClaimPricingRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int result = super.hashCode();
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "OppsClaimPricingRequest()";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public OppsClaimPricingRequest() {
    }
}
